apiVersion: v1
kind: Service
metadata:
  name: svc-2
spec:
  selector:
    app: pod
  ports:
    # Cluster 내부 접속 용도 포트
    - port: 9000
      # 이 서비스가 타겟으로 하는 서비스들이 열어놓은 포트
      targetPort: 8080
      # 각 노드에서 여기로 연결할 포트
      nodePort: 30000
  type: NodePort
  externalTrafficPolicy: Local
