apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: container1
      image: tmkube/p8000
      ports:
        - containerPort: 8000
    - name: container2
      image: tmkube/p8080
      ports:
        - containerPort: 8080
