version: "3.7"

services:
  pyspark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ".:/home/jovyan/work"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
