apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-2
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node-1
  containers:
    - name: container1
      image: tmkube/init
      volumeMounts:
        - name: host-path
          mountPath: /mount1
    - name: container2
      image: tmkube/init
      volumeMounts:
        - name: host-path
          mountPath: /mount2
  volumes:
    - name: host-path
      hostPath:
        path: /node-v
        # 해당 path가 없으면 생성한다.
        # 따라서 노드에 미리 만들어놓을 필요가 없음.
        type: DirectoryOrCreate
