apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-1
spec:
  containers:
    - name: container
      image: tmkube/init
      volumeMounts:
        - name: pvc-pv
          mountPath: /mount3
      volumes:
        - name: pvc-pv
          persistentVolumeClaim:
            claimName: pvc-01
