apiVersion: v1
kind: Pod
metadata:
  name: pod_with_resource_limit
spec:
  containers:
    - name: container
      image: tmkube/init
      resources:
        requests:
          memory: 2Gi
        limits:
          memory: 3Gi
